github.api.base.url=https://api.github.com
github.api.token=${GITHUB_API_TOKEN}
github.api.issue.search.path=/search/issues
github.api.issue.search.page.size=100
github.api.issue.search.max.retries=3
github.api.issue.search.retry.base.delay.millis=100
github.api.issue.search.retry.max.delay.millis=1000
github.issue.search.query.language=Java
github.issue.search.query.label=good first issue
github.issue.search.query.state=open
github.issue.search.query.createdAfter=2026-06-10
github.issue.search.query.createdAfter.lookBack.enabled=true
github.issue.search.query.createdAfter.lookBack.hours=3
github.issue.search.query.unassigned=true
github.issue.report.output.path=dist/digest.html