github.api.base.url=https://api.github.com
github.api.token=${GITHUB_API_TOKEN}
github.api.issue.search.path=/search/issues
github.api.issue.search.page.size=100
github.issue.search.query.language=Java
github.issue.search.query.label=good first issue
github.issue.search.query.state=open
github.issue.search.query.createdAfter=2026-06-10
github.issue.search.query.unassigned=true
github.issue.report.output.path=dist/digest.html