package io.github.khawajaabdullah;

import java.util.regex.Pattern;

public final class Constant {

  public static final String APPLICATION_DEFAULT_PROPERTIES_FILE_PATH = "application-default.properties";

  public static final String GITHUB_API_BASE_URL_KEY = "github.api.base.url";
  public static final String GITHUB_API_TOKEN = "github.api.token";
  public static final String GITHUB_API_ISSUE_SEARCH_PATH_KEY = "github.api.issue.search.path";
  public static final String GITHUB_API_ISSUE_SEARCH_PAGE_SIZE_KEY = "github.api.issue.search.page.size";

  public static final String GITHUB_ISSUE_SEARCH_QUERY_LANGUAGE_KEY = "github.issue.search.query.language";
  public static final String GITHUB_ISSUE_SEARCH_QUERY_LABEL_KEY = "github.issue.search.query.label";
  public static final String GITHUB_ISSUE_SEARCH_QUERY_STATE_KEY = "github.issue.search.query.state";
  public static final String GITHUB_ISSUE_SEARCH_QUERY_CREATED_AFTER_KEY = "github.issue.search.query.createdAfter";
  public static final String GITHUB_ISSUE_SEARCH_QUERY_UNASSIGNED_KEY = "github.issue.search.query.unassigned";

  public static final String GITHUB_ISSUE_REPORT_OUTPUT_PATH_KEY = "github.issue.report.output.path";

  public static final String ACCEPT_HEADER = "Accept";
  public static final String AUTHORIZATION_HEADER = "Authorization";
  public static final String GITHUB_MEDIA_TYPE = "application/vnd.github+json";

  public static final String GITHUB_ISSUE_FILTERED_RESPONSE_REGEX = "\"html_url\"\\s*:\\s*\"([^\"]+)\".*?\"title\"\\s*:\\s*\"([^\"]+)\"";
  public static final Pattern GITHUB_ISSUE_FILTERED_RESPONSE_PATTERN = Pattern.compile(Constant.GITHUB_ISSUE_FILTERED_RESPONSE_REGEX);

  public static final String GITHUB_ISSUE_REPORT_HTML_TEMPLATE = """
      <!DOCTYPE html>
      <html>
      <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Contribot Nano Issue Digest</title>
      </head>
      <body style="margin: 0; padding: 40px 20px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; background-color: #f6f8fa; color: #24292f; -webkit-font-smoothing: antialiased;">
          <div style="max-width: 680px; margin: 0 auto; background-color: #ffffff; border: 1px solid #d0d7de; border-radius: 8px; padding: 32px; box-shadow: 0 4px 12px rgba(27, 31, 35, 0.04);">
      
              <div style="border-bottom: 1px solid #d0d7de; padding-bottom: 20px; margin-bottom: 24px;">
                  <h1 style="font-size: 22px; font-weight: 600; margin: 0; color: #24292f; letter-spacing: -0.5px;">
                      🚀 Contribot Nano Digest
                  </h1>
                  <p style="font-size: 14px; color: #57606a; margin: 6px 0 0 0; line-height: 1.5;">
                      Lightweight Github issue tracker for open source enthusiasts
                  </p>
              </div>
      
              <div style="overflow-x: auto;">
                  <table style="width: 100%%; border-collapse: collapse; text-align: left;">
                      <thead>
                          <tr style="border-bottom: 2px solid #d0d7de;">
                              <th style="padding: 12px 8px; font-size: 13px; font-weight: 600; color: #57606a; text-transform: uppercase; letter-spacing: 0.5px;">Filtered Issues</th>
                          </tr>
                      </thead>
                      <tbody>
                          %s
                      </tbody>
                  </table>
              </div>
      
              <div style="margin-top: 32px; padding-top: 24px; border-top: 1px solid #d0d7de; text-align: center;">
                  <p style="font-size: 12px; color: #57606a; margin: 0; line-height: 1.6;">
                      Generated by <a href="https://github.com/khawaja-abdullah/contribot-nano" style="color: #0969da; text-decoration: none; font-weight: 600;">Contribot Nano</a>
                  </p>
              </div>
      
          </div>
      </body>
      </html>
      """;
  public static final String GITHUB_ISSUE_ROW_TEMPLATE = """
      <tr style="border-bottom: 1px solid #line-height: 1.5; border-color: #rgba(208,215,222,0.5);">
          <td style="padding: 16px 8px; vertical-align: middle;">
              <div style="font-size: 15px; font-weight: 600; color: #24292f; line-height: 1.4; word-break: break-word;">
                  %s
              </div>
          </td>
          <td style="padding: 16px 8px; vertical-align: middle; text-align: right;">
              <a href="%s" target="_blank" style="display: inline-block; padding: 5px 12px; font-size: 12px; font-weight: 500; line-height: 18px; color: #ffffff; background-color: #2da44e; border: 1px solid rgba(27,31,36,0.15); border-radius: 6px; text-decoration: none; white-space: nowrap;">
                  Contribute
              </a>
          </td>
      </tr>
      """;
  public static final String GITHUB_ISSUE_EMPTY_ROW_TEMPLATE = """
      <tr>
          <td colspan="2" style="padding: 32px 8px; text-align: center; font-size: 14px; color: #57606a; font-style: italic; background-color: #fafafa; border-radius: 6px;">
              No Github issues matched your specific query filters
          </td>
      </tr>
      """;

  private Constant() {
  }

}
