name: CI CD (Native)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@f60d4ea89f14098520aea588431217bbd9551570 # v1.6.5
        with:
          java-version: '21'
          distribution: 'graalvm'
          cache: 'maven'
      - name: Package (native)
        run: mvn clean package -Pnative -DskipTests
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: contribot-nano-native
          path: target/contribot-nano-native
  run:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: contribot-nano-native
          path: target/
      - name: Run
        env:
          GITHUB_API_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_ISSUE_SEARCH_QUERY_CREATEDAFTER_LOOKBACK_ENABLED: true
          GITHUB_ISSUE_SEARCH_QUERY_CREATEDAFTER_LOOKBACK_HOURS: 1
        run: |
          chmod +x ./target/contribot-nano-native
          ./target/contribot-nano-native